image: golang:latest

stages:
  - build
  - deploy

format:
  stage: build
  script:
    - test -z "$(gofmt -l ./)"

vet:
  stage: build
  script:
    - go vet -json ./... | tee vet-report.json
  artifacts:
    when: always
    paths:
      - vet-report.json
    expire_in: 1 hour

build:
  stage: build
  script:
    - go build ./...
  artifacts:
    untracked: true
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - echo "Deploying the app"
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - scp -i $ID_RSA -o StrictHostKeyChecking=no checkers $SERVER_USER@$SERVER_IP:/projects/aboo
