image: golang:latest

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - checkers
    expire_in: 1 hour
  script:
    - go build ./...

deploy:
  stage: deploy
  script:
    - echo "Deploying the app"
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - scp -i $ID_RSA -o StrictHostKeyChecking=no $CI_PROJECT_DIR/checkers $SERVER_USER@$SERVER_IP:/projects/aboo
