version: '3.1'
services:
  checker:
    image: registry.gitlab.com/aboo9442027/checker/checker-prod:latest
    build:
      dockerfile: docker/Dockerfile
    container_name: checker
    working_dir: /app
    ports:
      - '56033:8080'
