version: '3.1'
services:
  checkers:
    image: registry.gitlab.com/aboo9442027/checkers/checkers:latest
    build:
      dockerfile: docker/Dockerfile
    container_name: checkers
    working_dir: /app
    ports:
      - '56033:8080'
    restart: unless-stopped
